f = open('10.txt','w')
fn = open('10.txt','r') 
print("pointer's Position is ",f.tell())
f.write('hello\nworld\nPython\njava\nc++')
f.close()
fn = open('10.txt','r')
print(fn.read())
print("Current pointer's Position is ",fn.tell())
fn.close()
