tuple=("Bhagat Singh","Lakshmi bai","Lal Bahadur Shastri")
print(tuple)
print(tuple[0])
print(tuple[1:3])
print(tuple[2:])
print(tuple* 2)
tuple2=("Gandhi ji","Subas Bose","Jawahalal Nehru")
print(tuple + tuple2)      
